### ISSUE TITLE
Transactions does not load

### ISSUE THREAD

**Issue by andreas-barthel** [unification-com/web-wallet#49]
On the master-Branch and in the offcial Beta 0.19.1 :
The list of Transaction (Sent, Received does not loading).

![image](https://user-images.githubusercontent.com/34137982/109354007-6f63f900-787d-11eb-8f91-0ee4170f3f50.png)

In the console this error appears:

![image](https://user-images.githubusercontent.com/34137982/109354101-8f93b800-787d-11eb-9a83-cca3dd843f45.png)

I have tried to debug it, but Promises are not my friends :(
But here in Transactions.vue

![image](https://user-images.githubusercontent.com/34137982/109354271-d7b2da80-787d-11eb-9552-fdcc57b82951.png)

it seems that the promise of the transactions are not properly resolved and txRes.result is undefined
But the response from API seems to be fine:

![image](https://user-images.githubusercontent.com/34137982/109354577-5740a980-787e-11eb-96a6-032f16429c40.png)

**Comment by Codegnosis** [comment]
Thanks - fixed in [PR51](https://github.com/unification-com/web-wallet/pull/51)
